language: go

go:
    - 1.5

before_install:
  - go get github.com/tcnksm/ghr

install:
    go get -t ./...

after_success:
    make release
    ghr  --username sentinel-tools --token $GITHUB_TOKEN $(cat .version) eventilator-$(cat .version).tar.gz
