language: go

go:
    - 1.5

before_install:
  - go get github.com/tcnksm/ghr

after_success:
  - go build 
  - go build  -o reconfigurator
  - ghr  --username sentinel-tools --token $GITHUB_TOKEN $(cat .version) eventilator reconfigurator.conf reconfigurator
